### ISSUE TITLE
user can't use the path to the flow using backslash

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/cloud-slang#472] opened 2015-10-29 09:46 UTC
when running:
cslang>run --f C:\Roi\Tasks\cloudSlang\cslang-cli\cslang\cloud-slang-content-master\content\io\cloudslang\base\files\write_to_file.sl
user gets:
Command failed java.lang.IllegalArgumentException: File: write_to_file.sl was not found

workaround:user can switch all the slash into backslash

**Comment by oritstone** [comment] 2015-10-29 11:17
Duplicate of #212

**Closed by oritstone** 2015-10-29 11:17 UTC
