### ISSUE TITLE
cloudSlang started to run and then got stuck

### ISSUE THREAD

**Issue by gseffy** [CloudSlang/cloud-slang#193] opened 2015-03-30 11:12 UTC
I tried to run a simple flow from docker image. The flow started to run and then got stuck after:
Database name is: H2 databaseMajorVersion is: 1

The log file:
2015-03-30 11:05:41:435 0    [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from URL [jar:file:/cslang/cslang/lib/cloudslang-cli-0.7.3.jar!/META-INF/spring/spring-shell-plugin.xml]
2015-03-30 11:05:41:811 376  [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from URL [jar:file:/cslang/cslang/lib/cloudslang-cli-0.7.3.jar!/META-INF/spring/slangCliContext.xml]
2015-03-30 11:05:41:943 508  [main] INFO  io.cloudslang.schema.ScoreNamespaceHandler  - Registering Score namespace handler
2015-03-30 11:05:42:026 591  [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from class path resource [META-INF/spring/score/context/scoreRepositoryContext.xml]
2015-03-30 11:07:49:336 127901 [main] WARN  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Ignored XML validation warning
org.xml.sax.SAXParseException; systemId: http://www.springframework.org/schema/tx/spring-tx.xsd; lineNumber: 12; columnNumber: 150; schema_reference.4: Failed to read schema document 'http://www.springframework.org/schema/tool/spring-tool-4.1.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.warning(ErrorHandlerWrapper.java:99)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:433)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4162)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaWarning(XSDHandler.java:4157)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument1(XSDHandler.java:2490)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2187)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.resolveSchema(XSDHandler.java:2078)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.constructTrees(XSDHandler.java:1008)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:620)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:616)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2453)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1772)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:766)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:347)
        at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:76)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadDocument(XmlBeanDefinitionReader.java:429)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:216)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:187)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:251)
        at io.cloudslang.schema.EngineBeanDefinitionParser.loadContexts(EngineBeanDefinitionParser.java:140)
        at io.cloudslang.schema.EngineBeanDefinitionParser.parseInternal(EngineBeanDefinitionParser.java:118)
        at org.springframework.beans.factory.xml.AbstractBeanDefinitionParser.parse(AbstractBeanDefinitionParser.java:60)
        at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1426)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1416)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:103)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:510)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:250)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:191)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:176)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:103)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:510)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:216)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:187)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:251)
        at org.springframework.shell.Bootstrap.<init>(Bootstrap.java:101)
        at org.springframework.shell.Bootstrap.<init>(Bootstrap.java:76)
        at org.springframework.shell.Bootstrap.main(Bootstrap.java:58)
Caused by: java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:637)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:582)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:685)
        at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
        at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2175)
        ... 55 more
2015-03-30 11:07:50:685 129250 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from class path resource [META-INF/spring/score/context/scoreEngineSchedulerContext.xml]
2015-03-30 11:07:50:786 129351 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from class path resource [META-INF/spring/score/context/scoreWorkerSchedulerContext.xml]
2015-03-30 11:07:50:890 129455 [main] INFO  org.springframework.context.support.GenericApplicationContext  - Refreshing org.springframework.context.support.GenericApplicationContext@7fa17f0: startup date [Mon Mar 30 11:07:50 GMT 2015]; root of context hierarchy
2015-03-30 11:07:51:641 130206 [main] INFO  org.springframework.context.support.PropertySourcesPlaceholderConfigurer  - Loading properties file from class path resource [application.properties]
2015-03-30 11:07:52:554 131119 [main] INFO  org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory  - Creating embedded database 'testdb'
2015-03-30 11:07:53:514 132079 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - Successfully acquired change log lock
2015-03-30 11:07:53:766 132331 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - Creating database history table with name: DATABASECHANGELOG
2015-03-30 11:07:53:792 132357 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - Reading from DATABASECHANGELOG
2015-03-30 11:07:53:795 132360 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - Reading from DATABASECHANGELOG
2015-03-30 11:07:54:025 132590 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::Manually create the hibernate auto-increment table for OO::hibernate ran successfully in 11ms
2015-03-30 11:07:54:078 132643 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::Create OO_EXECUTION_STATE::engine ran successfully in 19ms
2015-03-30 11:07:54:134 132699 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::create OO_EXECUTION_STATES::engine ran successfully in 24ms
2015-03-30 11:07:54:160 132725 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::create OO_EXECUTION_QUEUES::engine ran successfully in 7ms
2015-03-30 11:07:54:178 132743 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::Create OO_SUSPENDED_EXECUTIONS::engine ran successfully in 9ms
2015-03-30 11:07:54:194 132759 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::Create OO_FINISHED_BRANCHES::engine ran successfully in 8ms
2015-03-30 11:07:54:224 132789 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::create OO_PARTITION_GROUPS table::engine ran successfully in 21ms
2015-03-30 11:07:54:250 132815 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::create OO_RUNNING_EXECUTION_PLANS::engine ran successfully in 8ms
2015-03-30 11:07:54:282 132847 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::add table OO_VERSION_COUNTERS::engine ran successfully in 17ms
2015-03-30 11:07:54:343 132908 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::create OO_WORKER_NODES::engine ran successfully in 38ms
2015-03-30 11:07:54:383 132948 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - ChangeSet classpath:/META-INF/database/score.changes.xml::create OO_WORKER_LOCKS::engine ran successfully in 13ms
2015-03-30 11:07:54:398 132963 [main] INFO  liquibase.ext.logging.LiquibaseLogger  - Successfully released change log lock
2015-03-30 11:07:54:449 133014 [main] INFO  org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory  - Creating embedded database 'testdb'
2015-03-30 11:07:54:820 133385 [main] INFO  org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean  - Building JPA container EntityManagerFactory for persistence unit 'default'
2015-03-30 11:07:54:954 133519 [main] INFO  org.hibernate.annotations.common.Version  - HCANN000001: Hibernate Commons Annotations {4.0.2.Final}
2015-03-30 11:07:54:968 133533 [main] INFO  org.hibernate.Version  - HHH000412: Hibernate Core {4.2.16.Final}
2015-03-30 11:07:54:970 133535 [main] INFO  org.hibernate.cfg.Environment  - HHH000206: hibernate.properties not found
2015-03-30 11:07:54:980 133545 [main] INFO  org.hibernate.cfg.Environment  - HHH000021: Bytecode provider name : javassist
2015-03-30 11:07:55:028 133593 [main] INFO  org.hibernate.ejb.Ejb3Configuration  - HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2015-03-30 11:07:55:282 133847 [main] INFO  org.hibernate.service.jdbc.connections.internal.ConnectionProviderInitiator  - HHH000130: Instantiating explicit connection provider: org.hibernate.ejb.connection.InjectedDataSourceConnectionProvider
2015-03-30 11:07:55:371 133936 [main] INFO  org.hibernate.dialect.Dialect  - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2015-03-30 11:07:55:922 134487 [main] INFO  org.hibernate.engine.transaction.internal.TransactionFactoryInitiator  - HHH000268: Transaction strategy: org.hibernate.engine.transaction.internal.jdbc.JdbcTransactionFactory
2015-03-30 11:07:55:933 134498 [main] INFO  org.hibernate.hql.internal.ast.ASTQueryTranslatorFactory  - HHH000397: Using ASTQueryTranslatorFactory
2015-03-30 11:07:56:023 134588 [main] INFO  org.hibernate.validator.internal.util.Version  - HV000001: Hibernate Validator 4.3.0.Final
2015-03-30 11:07:56:403 134968 [main] INFO  org.hibernate.tool.hbm2ddl.SchemaValidator  - HHH000229: Running schema validator
2015-03-30 11:07:56:404 134969 [main] INFO  org.hibernate.tool.hbm2ddl.SchemaValidator  - HHH000102: Fetching database metadata
2015-03-30 11:07:56:430 134995 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_EXECUTION_STATE
2015-03-30 11:07:56:430 134995 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [execution_object, id, status, execution_id, branch_id]
2015-03-30 11:07:56:441 135006 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_FINISHED_BRANCHES
2015-03-30 11:07:56:441 135006 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [suspended_execution_id, id, split_id, execution_id, branch_exception, branch_id, branch_context]
2015-03-30 11:07:56:451 135016 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_PARTITION_GROUPS
2015-03-30 11:07:56:451 135016 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [id, last_roll_time, time_threshold, active_partition, name, size_threshold, group_size]
2015-03-30 11:07:56:461 135026 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_RUNNING_EXECUTION_PLANS
2015-03-30 11:07:56:461 135026 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [id, result, execution_plan_zipped, uuid, execution_plan]
2015-03-30 11:07:56:479 135044 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_SUSPENDED_EXECUTIONS
2015-03-30 11:07:56:479 135044 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [execution_object, id, split_id, execution_id, number_of_branches]
2015-03-30 11:07:56:503 135068 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_VERSION_COUNTERS
2015-03-30 11:07:56:504 135069 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [id, counter_version, counter_name]
2015-03-30 11:07:56:511 135076 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_WORKER_GROUPS
2015-03-30 11:07:56:519 135084 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [group_name, worker_id]
2015-03-30 11:07:56:537 135102 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_WORKER_LOCKS
2015-03-30 11:07:56:537 135102 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [id, uuid]
2015-03-30 11:07:56:553 135118 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000261: Table found: TESTDB.PUBLIC.OO_WORKER_NODES
2015-03-30 11:07:56:553 135118 [main] INFO  org.hibernate.tool.hbm2ddl.TableMetadata  - HHH000037: Columns: [bulk_number, os, ack_time, ack_version, status, is_active, jvm, host_name, password, wrv, id, is_deleted, dot_net_version, description, uuid, install_path]
2015-03-30 11:07:58:475 137040 [main] INFO  io.cloudslang.engine.partitions.services.PartitionTemplateImpl  - Registering callback class ExecutionStatesCallback for partition group [null]
2015-03-30 11:07:58:651 137216 [main] INFO  io.cloudslang.engine.partitions.services.PartitionServiceImpl  - Partition group [OO_EXECUTION_STATES] was created, with group size 2, and timeThreshold -1, and sizeThreshold 50000
2015-03-30 11:07:59:267 137832 [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler  - Initializing ExecutorService  'scoreOrchestratorScheduler'
2015-03-30 11:07:59:429 137994 [main] INFO  io.cloudslang.worker.management.services.WorkerManager  - Initialize worker with UUID: -1
2015-03-30 11:07:59:498 138063 [main] INFO  io.cloudslang.worker.management.services.InBuffer  - InBuffer capacity is set to :500, coolDownPollingMillis is set to :200
2015-03-30 11:07:59:508 138073 [main] INFO  io.cloudslang.worker.management.services.OutboundBufferImpl  - maxBufferWeight = 15000
2015-03-30 11:07:59:557 138122 [main] INFO  io.cloudslang.worker.management.WorkerRegistration  - Registering worker -1
2015-03-30 11:07:59:557 138122 [main] INFO  io.cloudslang.worker.management.WorkerRegistration  - Creating worker...
2015-03-30 11:07:59:681 138246 [main] INFO  io.cloudslang.worker.management.WorkerRegistration  - Worker [-1] registered and activated
2015-03-30 11:07:59:695 138260 [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler  - Initializing ExecutorService  'scoreWorkerScheduler'

**Comment by meirwah** [comment] 2015-03-30 11:14
@tudorlesan @orius123 @Bonczidai  do you remamber what causes his?

**Comment by Bonczidai** [comment] 2015-03-30 11:30
The error message from the beginning is mentioned in #167 , which introduces a very slow startup, but after that, the CLI should work ..

**Comment by gseffy** [comment] 2015-03-30 11:31
I waited more then an hour..

**Comment by orius123** [comment] 2015-03-30 11:36
Looks like a spring-hibernate adventure..
It seems that it can't find the scheme correctly, for some reason.
And also what does http is doing here?

**Comment by meirwah** [comment] 2015-03-30 11:42
didn't we solve this last time #167 by replacing the JYthon jar??

**Comment by orius123** [comment] 2015-03-30 11:46
I don't think so. I think jython was related to jline errors.

**Comment by meirwah** [comment] 2015-03-30 14:17
Please note this part : 

2015-03-30 11:05:42:026 591 [main] INFO org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from class path resource [META-INF/spring/score/context/scoreRepositoryContext.xml]
2015-03-30 11:07:49:336 127901 [main] WARN 

more then 2 min for loading scoreRepositoryContext.xm...

**Comment by meirwah** [comment] 2015-03-30 15:00
Also, it  seems to be looking for xsd of spring-tool-4.1, but we do not seem to have this jar in the classpath..

**Comment by meshipeer** [comment] 2015-04-06 07:20
during our bug hunt, Yaniv also phases this: Run cslang file from command line cause to Exception in the log and takes a lot of time. from the log: Failed to read schema document 'http://www.springframework.org/schema/tool/spring-tool-4.1.xsd'

**Comment by meirwah** [comment] 2015-04-06 12:13
seems to happen only in linux based systems, could not reproduce on win...
can yaniv verify @meshipeer ?

**Comment by meirwah** [comment] 2015-04-06 13:46
Opened a stackoverflow question on this : 
http://stackoverflow.com/questions/29471695/failed-to-read-schema-document-http-www-springframework-org-schema-tool-sprin/29472455#29472455

**Comment by meirwah** [comment] 2015-04-06 14:04
I think i found the issue, seems that we have dependency in spring-tx-4.1.4.RELEASE.jar, while all other(at least must) spring libs are at 4.0.8 version, seems like replacing in the classpath the jar to 4.0.8 fixes the issue...

**Comment by meirwah** [comment] 2015-04-06 14:06
It also seems to solve uptime for the CLI, it takes the CLI 2 min less to startup..

**Comment by orius123** [comment] 2015-04-06 16:39
We should use spring IO

**Comment by meirwah** [comment] 2015-04-06 19:21
fixed by #231

**Closed** 2015-04-07 12:24 UTC
Labels: bug hunt, in progress, P0
