### ISSUE TITLE
Truncated error message

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#203] opened 2015-04-02 08:58 UTC
I noticed a wierd kind of error. Tried running the run_command.sl operation and used a path with backslashes.

run --f C:\..\cloud-slang-content\content\io\cloudslang\base\cmd\run_command.sl --i command=ipconfig. This was the error:

"un_command.sl was not foundlegalArgumentException: File: cmd"
As you can see it's truncated not sure why that is.

If I use the same string with / instead of \ it works fine

**Comment by meirwah** [comment] 2015-04-02 09:01
the is because the "\r" is messing up the CLI parsing, you must use the Linux notion ("/") to avoid that..
@SamMarkowitz maybe we need this be more clear on docs?

**Comment by orius123** [comment] 2015-04-02 09:04
I think we should fix it.

**Comment by SamMarkowitz** [comment] 2015-04-02 09:05
The following is found in the Use The CLI section:

The usage of forward slashes (/) in all file paths is recommended even on Windows.

Where else can we mention it to make sure people don't miss it?

**Comment by tudorlesan** [comment] 2015-04-02 09:08
I thinking of changing the error message. That way anyone surely can't miss it. Though I'm not sure how this is implemented.

**Comment by meshipeer** [comment] 2015-04-14 15:30
Duplicate of #212

**Closed** 2015-06-03 13:41 UTC
Labels: bug
