### ISSUE TITLE
same python script is pending in CloudSlang

### ISSUE THREAD

**Issue by johanzilber** [CloudSlang/cloud-slang#657] opened 2016-04-18 10:13 UTC
The following cloudSlang script ‘[run_job.sl](https://www.dropbox.com/s/bgw31lu2wxpxnr8/run_job.sl?dl=0)’ invokes Jenkins job but never finishes successfully though the relevant Jenkins job is started and finished:
![cloud_slang_run_job_not_finished](https://cloud.githubusercontent.com/assets/18458403/14600535/cf10993e-0565-11e6-8afb-74a972bbdac1.PNG)

While the identical python script ‘[run_job.py](https://www.dropbox.com/s/f8pcjv0npgwfzwm/run_job.py?dl=0)’ invokes the job and finishes successfully when the job is done:
![python_run_job_finished](https://cloud.githubusercontent.com/assets/18458403/14600521/c11fc386-0565-11e6-8952-0ea5fb7d128b.PNG)

**Comment by Bonczidai** [comment] 2016-04-26 08:44
hi @johanzilber 

- first of all, seems that you are not using the same script since the output is different
- can you please help me reproduce the error?
  - use [Jenkins Docker container](https://hub.docker.com/_/jenkins/) and let me know the version of it / necessary config details
  - which jenkinsapi version are you using for CloudSlang
  - CLI cmd for CS

**Comment by Bonczidai** [comment] 2016-04-26 08:45
another tip: check whether it's a proxy issue

**Comment by Bonczidai** [comment] 2016-05-05 09:02
@johanzilber any update here?

**Comment by Bonczidai** [comment] 2016-05-09 07:49
closing for now - please reopen if you can reproduce the problem with the upper tips

**Closed by Bonczidai** 2016-05-09 07:49 UTC
Labels: bug, Start Issue
