### ISSUE TITLE
Error message when missing --f is misleading

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang#243] opened 2015-04-13 07:57 UTC
Trying to run a flow without the --f produces a misleading error message about quiet mode:
![image](https://cloud.githubusercontent.com/assets/9436355/7111749/d1b4d86c-e1cb-11e4-9ddd-38c3e4d22ff1.png)

**Comment by Bonczidai** [comment] 2016-03-08 13:45
duplicate of #470 , solved

**Closed by Bonczidai** 2016-03-08 13:45 UTC
Labels: bug, Usability - CLI
