### ISSUE TITLE
Outputs that take their values from sensitive inputs are displayed in plain text in drill-down.

### ISSUE THREAD

**Issue by arikye** [CloudSlang/cloud-slang#908] opened 2016-10-06 12:35 UTC
**ACTUAL BEHAVIOR:** 
When running a CSL flow that has a step with outputs that take their value directly from sensitive inputs, these outputs display the values in drill-down / step details as plain text.
 
There are two scenarios when this occurs:
               1. The value for the sensitive input is directly assigned in Web Studio in the operation's Inputs tab.
               2. The value for the sensitive input is taken from a non-sensitive system property whether a value for it is assigned in WebStudio or in Central after deployment.
 
Note @2: If the system property file is marked as sensitive in Web Studio, then the outputs will be obfuscated in Central / Drill Down whether has given a value for the system property in Web Studio or has left the system property without a value and set it in Central instead.

**EXPECTED BEHAVIOR:** 
The outputs' values should be obfuscated.

**HOW-TO-REPRODUCE:** 
1. Create a flow in Webstudio that contains the ssh_command operation.
2. Assign a value for the input "password" in the Inputs tab for this operation. (this input is marked as Sensitive)
3. Create an output for this operation that takes it's value directly from the "password" input.
4. Deploy the content in Central and run the flow.
5. Go to drill-down of the execution.
6. Notice that the Step Results (the operation's output) display the value in plain text.

[](https://quixy.prp.ext.hpe.com/quixy/query/detail.php?ISSUEID=QCCR8C32351)

**Comment by meshipeer** [comment] 2016-10-10 08:11
this is by design - closing

**Closed by meshipeer** 2016-10-10 08:11 UTC
