### ISSUE TITLE
Change 'fromInputs' key to executable name

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#258] opened 2015-04-16 12:10 UTC
instead of using this not so nice key, 
we can use the executable name.
i.e

```yaml
operation:
  name: baba
  inputs:
    - some_input
...
  publish:
    - some_output: baba['some_input']
```

**Comment by oritstone** [comment] 2015-04-16 12:36
Duplicate of #196

**Closed** 2015-04-16 12:39 UTC
Labels: enhancement
