### ISSUE TITLE
SlangCLI won't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#168] opened 2015-03-17 21:21 UTC
I tried getting the SlangCLI on Ubuntu 14.04 and it fails everytime with this error:

score-language/score-lang-cli/target/slang/bin$ ./slang
Database name is: H2 databaseMajorVersion is: 1
[ERROR] Terminal initialization failed; falling back to unsupported
java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected
	at jline.TerminalFactory.create(TerminalFactory.java:101)
	at jline.TerminalFactory.get(TerminalFactory.java:158)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:229)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:209)
	at org.springframework.shell.core.JLineShell.createConsoleReader(JLineShell.java:250)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:112)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "Spring Shell" java.lang.IncompatibleClassChangeError: Found class jline.Terminal, but interface was expected
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:230)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:221)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:209)
	at org.springframework.shell.core.JLineShell.createConsoleReader(JLineShell.java:250)
	at org.springframework.shell.core.JLineShell.run(JLineShell.java:112)
	at java.lang.Thread.run(Thread.java:745)

. I got it using all three methods: cloned repo, SlangCLI download link on openscore.io and npm -g slang-cli and the results were the same. Any help is appreciated

**Comment by meirwah** [comment] 2015-03-18 08:22
which java version are you using on that machine???

**Comment by tudorlesan** [comment] 2015-03-18 09:45
this is what I used to install it "sudo apt-get install openjdk-7-jre" so latest Java 7

**Comment by meirwah** [comment] 2015-03-18 09:53
run java -version in the CMD

**Comment by tudorlesan** [comment] 2015-03-18 09:57
laptop is at home. I will when I leave work..

**Comment by meirwah** [comment] 2015-03-18 10:02
adding @seffy

**Comment by meirwah** [comment] 2015-03-18 10:03
adding @gseffy , do you have same issue?

**Comment by meirwah** [comment] 2015-03-18 10:04
and which version of slang are you using?

**Comment by tudorlesan** [comment] 2015-03-18 10:29
@meirwah latest released on our website and also latest from master. Can I check slang version if CLI is not starting and no poms either?

**Comment by gseffy** [comment] 2015-03-18 11:10
I am using the latest version (git clone https://github.com/openscore/score-language.git) on centos.
getting the same error....

**Comment by orius123** [comment] 2015-03-18 11:35
Can you please test if upgrading jython to beta 4. Solves it

**Comment by meirwah** [comment] 2015-03-18 12:31
version on website : 
https://github.com/openscore/score-language/releases/download/slang-CLI-v0.2.1/score-lang-cli.zip

seem to work on ubuntu, verified just now...

**Comment by meirwah** [comment] 2015-03-18 12:32
Ubuntu version 10.04
java version "1.7.0_65"

**Comment by tudorlesan** [comment] 2015-03-18 12:32
I'll test it as soon as I get home, I'm using 14.04 though

**Comment by meirwah** [comment] 2015-03-18 12:33
what Terminal are you using to run SSH from windows to Linux machine?

**Comment by tudorlesan** [comment] 2015-03-18 12:34
I'm trying to start slang directly on ubuntu, so no terminal from windows to linux.

**Comment by meirwah** [comment] 2015-03-18 12:39
Also last version : 
https://github.com/openscore/score-language/releases/download/slang_travis_upload_test_V0.93/slang-cli.zip

works for me on same machine...

**Comment by tudorlesan** [comment] 2015-03-18 12:41
I tested that and it doesn't work. I'm starting to think maybe I'm missing some dependencies or maybe the actual version 14.04 if not supported :-?

**Comment by meirwah** [comment] 2015-03-18 12:42
tested it on 14.04, it is something else...

**Comment by tudorlesan** [comment] 2015-03-18 12:45
I'll try updating to jython beta 4, maybe it works this way :-??

**Comment by meirwah** [comment] 2015-03-18 12:45
please try

**Comment by meirwah** [comment] 2015-03-18 12:53
please look at : 
JAVAHOME/jre/lib/ext (example: /usr/local/java/jre/lib/ext)

see if you have a Jline Jar there...

**Comment by tudorlesan** [comment] 2015-03-18 16:25
@meirwah I'm looking at that path and no Jline Jar is there

**Comment by meirwah** [comment] 2015-03-18 16:30
adding @orius123 to this thread.. this is blocking both Seffy and Tudor.
any idea?

**Comment by tudorlesan** [comment] 2015-03-18 16:48
@meirwah I have java 1.7.0_75 on this machine. @orius123 I downloaded Jython 2.7beta4 (used the installer) and still doesn't work.

**Comment by meirwah** [comment] 2015-03-18 16:54
try to change to java 1.7.0_65

**Comment by tudorlesan** [comment] 2015-03-18 17:36
I'm not sure how I can change the version. I've been trying with no success. do you think it might have something to do with the fact that I have java-7-openjdk-amd64 instead of the Oracle one?

**Comment by orius123** [comment] 2015-03-18 18:58
I meant updating jython version in the pom

**Comment by meirwah** [comment] 2015-03-18 19:02
he can just replace the jar in the lib folder.. that should be enough no?

**Comment by meirwah** [comment] 2015-03-18 19:03
@tudorlesan try to change the jars in the lib folder (old Jython Jar with new Jython Jar )

**Comment by tudorlesan** [comment] 2015-03-18 19:35
@meirwah @orius123 that worked ! thanks a million :d

**Comment by orius123** [comment] 2015-03-18 19:46
Don't thank as so fast.. beta 4 has a other problems. We are waiting for the final release

**Comment by tudorlesan** [comment] 2015-03-18 19:50
What kind of problems? Won't I be able to run our flows from slang-content? if so, do you also have beta4 on ubuntu?

**Comment by tudorlesan** [comment] 2015-03-18 20:05
I don't know if this has something to do with jython beta4 or if it's some other problem. But I'm supposed to start the CLI with the commands from terminal directly. something like 
"bash slang help". The terminal shows the result correctly but then throws this error:

AllowedException: Error creating bean with name 'transactionManager': Singleton bean creation not allowed while the singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:215)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:198)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.determineTransactionManager(TransactionAspectSupport.java:334)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:252)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy78.updateEnvironmentParams(Unknown Source)
	at org.openscore.worker.management.services.WorkerManager$1.run(WorkerManager.java:186)
	at java.lang.Thread.run(Thread.java:745)

**Comment by orius123** [comment] 2015-03-18 20:40
The problem is related to serialization. Submitted a PR and they merged it. Hope cli will work with the stable release.

**Comment by tudorlesan** [comment] 2015-03-18 20:41
yep, I got the latest cli(master) and it's working fine. thanks

**Comment by meirwah** [comment] 2015-03-18 20:47
can we create a release with this fix? so seffy can use it too?

**Comment by tudorlesan** [comment] 2015-03-18 20:51
I can send her an archive with slang-cli with jython beta4 in the lib folder :-??.don't know how to make a release..

**Comment by meirwah** [comment] 2015-03-18 20:55
upload it to dropbox or google drive... and send here the link..

**Comment by tudorlesan** [comment] 2015-03-18 21:16
https://dl.dropboxusercontent.com/u/104181487/slang.tar.gz

**Comment by orius123** [comment] 2015-03-19 02:28
We reverted to beta 3 on purpose. There are serialization issues with python strings.
Does loops and long flows also work for you?

**Comment by tudorlesan** [comment] 2015-03-19 08:13
@orius123 I didn't get to test them. I only tested one operation and I noticed that the behavior is different from Windows to Linux. 

I tested less_than_percentage.sl which has the output "result". One of the cases of the operation leaves this output as None. In this case, on Windows the output is skipped and not present in the execution.log while on Linux the output appears in the execution.log as result=null and a NullPointerException is thrown.

I solved this on Linux by just assigning the empty string instead of None to result first, then changing it to boolean depending on the outcome. But I'm not sure why it's different from one OS to another.

Also, is there anyway of making beta3 work on linux?

**Comment by orius123** [comment] 2015-03-19 08:57
You can run it on my machine :smile: 
I guess we can somehow, but we need to find a way to reproduce it

**Comment by tudorlesan** [comment] 2015-03-19 09:00
ok :) I have to speak to you on that

**Comment by gseffy** [comment] 2015-03-19 14:19
@tudorlesan the link is working find but it is a old slang version, the flows I am using are not this version can you give me a more recent version?

**Comment by meirwah** [comment] 2015-03-19 14:20
@orius123 can you help?

**Comment by orius123** [comment] 2015-03-19 14:24
Try getting the latest release from score language repo.

**Comment by meirwah** [comment] 2015-03-19 14:38
but will it work @orius123 ?? it will have the same issue (JLine) no?

**Comment by gseffy** [comment] 2015-03-19 14:46
yes already tried it...

**Comment by meirwah** [comment] 2015-03-19 14:47
:+1:

**Comment by gseffy** [comment] 2015-03-19 14:48
I meant that I tried it and it didn't worked got the same exception..

**Comment by meirwah** [comment] 2015-03-19 14:50
ohhh...

**Comment by meirwah** [comment] 2015-03-19 16:31
@gseffy , here is a new version:
https://www.dropbox.com/s/o9ozi8tjtikyl9r/slang-cli.zip?dl=0

**Comment by meirwah** [comment] 2015-04-07 12:41
@tudorlesan is this issue stil relevent? can we close it?

**Comment by tudorlesan** [comment] 2015-04-08 07:55
@meirwah  it can be closed

**Closed** 2015-04-08 08:23 UTC
Labels: help wanted
