### ISSUE TITLE
release artifacts is wrong 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#450] opened 2015-09-24 07:25 UTC
Please look : 
![image](https://cloud.githubusercontent.com/assets/6059211/10067590/7f652682-62a6-11e5-9899-d469371e6b06.png)

version 0.8.0.1 is missing CLi with content (both Tar and ZIP)

**Comment by oritstone** [comment] 2015-09-24 15:15
Duplicate of #452

**Closed** 2015-09-24 15:15 UTC
Labels: bug
